language: python
cache: pip

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
    - python: 3.6
    - python: 3.5
    - python: 2.7

install:
  - pip install -U pip
  - pip install -e .
  - pip install -U flake8 pytest pytest-cov

script:
  # Unit tests
  - pytest --cov citybikes

  # Static analysis
  - flake8 --statistics --count
